import type { Case } from "@/types";

export const mockCases: Case[] = [
  {
    id: "C-2023-001",
    species: "Canine",
    name: "Bella",
    age: "4 years",
    owner: "Sarah Jenkins",
    complaint: "Acute vomiting and lethargy for 24 hours, refusal to eat.",
    status: "In Progress",
    createdAt: "2023-10-24",
  },
  {
    id: "C-2023-002",
    species: "Feline",
    name: "Luna",
    age: "2 years",
    owner: "Michael Chang",
    complaint: "Routine vaccination and annual checkup.",
    status: "Completed",
    createdAt: "2023-10-23",
  },
  {
    id: "C-2023-003",
    species: "Canine",
    name: "Max",
    age: "7 years",
    owner: "David Miller",
    complaint: "Limping on hind left leg after park activity.",
    status: "New",
    createdAt: "2023-10-25",
  },
  {
    id: "C-2023-004",
    species: "Avian",
    name: "Tweety",
    age: "18 months",
    owner: "Emma Wilson",
    complaint: "Feather plucking and behavioral changes.",
    status: "New",
    createdAt: "2023-10-25",
  },
  {
    id: "C-2023-005",
    species: "Feline",
    name: "Oliver",
    age: "10 years",
    owner: "Robert Brown",
    complaint: "Dental cleaning follow-up, gum redness noted.",
    status: "Completed",
    createdAt: "2023-10-20",
  },
];
